# Generated by Django 4.1.5 on 2023-09-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='currentstock',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Red', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='column',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='row',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stockreminder',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='validity',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='walldirection',
            field=models.CharField(default='E', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
