# Generated by Django 4.1.5 on 2023-09-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_quantity_product_currentstock_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.FloatField(default='empty', max_length='30'),
        ),
    ]
